---
- name: 'Checking if service_files is set'
  fail:
    msg: 'service_files variable is not set'
  when: service_files is not defined

- name: 'Checking if name and priority is set'
  fail:
    msg: 'name or priority variable is not set'
  when: (item.name is undefined) or (item.priority is undefined)
  with_items: '{{service_files}}'

- name: 'Checking if params is set'
  fail:
    msg: 'params variable is not set'
  when: (item.params is undefined)
  with_items: '{{service_files}}'

- name: 'Creating remote directory'
  file:
    path: '{{systemd_directory}}/{{service_name}}.service.d'
    state: directory
    mode: '0755'

- name: 'Creating configuration file on: {{systemd_directory}}/{{service_name}}.service.d'
  template:
    src: services.j2
    dest: '{{systemd_directory}}/{{service_name}}.service.d/{{item.priority}}-{{item.name}}.conf'
    owner: root
    group: root
    mode: '0644'
  vars:
    template_params: '{{item.params}}'
  with_items: '{{service_files}}'
  notify:
    - reload systemd
    - restart service